runtime defaults.vim

set number
set hlsearch
set signcolumn=yes

set autoindent
set smartindent
set noexpandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

set undofile

highlight Comment cterm=italic

" `<C-E>` is already mapped to `<END>`
cnoremap <C-A> <HOME>

call plug#begin()

" List your plugins here
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'

Plug 'dense-analysis/ale'
call plug#end()
