syntax on

set number
set hlsearch
set signcolumn=yes

set autoindent
set smartindent
set noexpandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

set undofile

set backspace=indent,eol,start

highlight Comment cterm=italic

" `<C-E>` is already mapped to `<END>`
cnoremap <C-A> <HOME>

autocmd Filetype gitcommit setlocal spell textwidth=80
